# amuse configuration generated by ./configure from config.mk.in

PYTHON=/usr/bin/python3
CODE_GENERATOR=amusifier

#
# PYTHON embedding
#
PYTHON_DEV=no
CYTHON=
PYTHONCONFIG='no'
PYTHONDEV_CFLAGS=
PYTHONDEV_LDFLAGS=


#
# Compilers, for compiling without MPI
# these compilers must be the same or compatible with
# the mpi compilers
#
CXX=g++
CC=gcc
FC=gfortran
GFORTRAN_VERSION=9.3.0
IFORT_VERSION=
FC_ISO_C_AVAILABLE=yes

#
# Default flags, append to these in the makefiles
#
CXXFLAGS=-g -O2 -fPIC
CFLAGS=-g -O2 -fPIC
FCFLAGS=-g -O2 -fPIC
LDFLAGS=

#
# MPI Compilers
#
MPI_ENABLED=yes
MPICXX=mpicxx
MPICC=mpicc
MPIFC=mpif90
MPIEXEC=/usr/bin/mpiexec

MPI_CFLAGS=-I/usr/lib/x86_64-linux-gnu/openmpi/include -pthread
MPI_CXXFLAGS=-I/usr/lib/x86_64-linux-gnu/openmpi/include -pthread
MPI_FCFLAGS=-pthread -I/usr/lib/x86_64-linux-gnu/openmpi/lib
MPI_CLIBS=-L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi
MPI_CXXLIBS=-L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi_cxx -lmpi
MPI_FCLIBS=-I/usr/lib/x86_64-linux-gnu/openmpi/lib -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

#
# Java
#
JAVA_ENABLED=no
JAVA=
JAVAC=
JAR=
JAVA_VERSION=

#
# OpenMP
#

OPENMP_ENABLED=yes
OPENMP_FCFLAGS=-fopenmp
OPENMP_CFLAGS=-fopenmp
    
#
# Libraries: FFTW, GSL, HDF5, CUDA, SAPPORO
#

FOUND_FFTW=yes
FFTW_FLAGS=
FFTW_LIBS=-lfftw3 -lfftw3_threads
    
FOUND_GSL=yes
GSL_FLAGS=
GSL_LIBS=-lgsl -lgslcblas -lm

FOUND_GMP=yes
GMP_FLAGS=
GMP_LIBS=-lgmp

FOUND_MPFR=yes
MPFR_FLAGS=
MPFR_LIBS=-lmpfr -lgmp

HDF5_FLAGS=-I/usr/include -I/usr/include/hdf5/serial
HDF5_LIBS= -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5_hl -lhdf5  -lpthread -lsz -lz -ldl -lm
HDF5_FFLAGS= -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -I/usr/lib/x86_64-linux-gnu/hdf5/serial
HDF5_FLIBS= -L/usr/lib/x86_64-linux-gnu/hdf5/serial  -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -lpthread -lsz -lz -ldl -lm

NETCDF_PREFIX=.
NETCDF_FLAGS=
NETCDF_LIBS=
NETCDFF_PREFIX=.
NETCDFF_FLAGS=
NETCDFF_LIBS=

CUDA_ENABLED=no
NVCC=
NVCC_FLAGS=
CUDA_TK=/NOCUDACONFIGURED
CUDA_LIBS=-L/NOCUDACONFIGURED cuda cudart

FOUND_CL=no
CL_LIBS=
CL_FLAGS=

SAPPORO_VERSION=light
SAPPORO_LIBS=-L${AMUSE_DIR}/lib/sapporo_light -lsapporo 

FS_FLAGS=-I$(AMUSE_DIR)/lib/forsockets
FS_LIBS=-L$(AMUSE_DIR)/lib/forsockets -lforsockets

SC_FLAGS=-I$(AMUSE_DIR)/lib/stopcond
SC_CLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcond
SC_FCLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcond
SC_MPI_CLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcondmpi
SC_MPI_FCLIBS=-L$(AMUSE_DIR)/lib/stopcond -lstopcondmpi

export PYTHON CXX CC FC CXXFLAGS CFLAGS FCFLAGS MPICXX MPICC MPIFC LDFLAGS
export JAVA JAVAC JAVAH JAR JAVA_FLAGS
export FS_FLAGS FS_LIBS SC_FLAGS SC_CLIBS SC_FCLIBS SC_MPI_CLIBS SC_MPI_FCLIBS
export FFTW_FLAGS FFTW_LIBS
export GSL_FLAGS GSL_LIBS
export HDF5_FLAGS HDF5_LIBS
export OPENMP_FCFLAGS OPENMP_CFLAGS
export NVCC CUDA_TK CUDA_LIBS CUDA_ENABLED
export SAPPORO_VERSION SAPPORO_LIBS
export MPICFLAGS MPICCFLAGS MPIFCFLAGS
export IFORT_VERSION
export NVCC_FLAGS
export PYTHONDEV_LIBS PYTHONDEV_CFLAGS PYTHONDEV_LIBS
export FC_ISO_C_ENABLED

ifdef AMUSE_DIR
export AMUSE_DIR
endif

